image: "registry.intelligent-conception.de/container_registry/container_registry/haskell-dev:lts-14.17"

testing:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$ACCESS_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - wget -q -O - --no-check-certificate https://www.lrde.epita.fr/repo/debian.gpg | apt-key add -
    - echo "deb http://www.lrde.epita.fr/repo/debian/ stable/" >> /etc/apt/sources.list
    - apt update
    - apt install -y spot

  script:
    - stack build --test
