cabal-version:      3.0
name:               hanoi
version:            0.2.0.1
synopsis:           Library for automata and the HOA format
description:        A library for ω-regular automata and processing of files in HOA format
maintainer:         Philippe Heim
author:             Felix Klein
                    Philippe Heim
                    Gideon Geier
                    Marvin Stenger
license:            MIT
license-file:       LICENSE
category:           Automata
build-type:         Simple


library

  ghc-options:
    -Wall
    -Wno-name-shadowing
    -Werror
    -Wwarn=unused-imports
    -Wwarn=unused-matches
    -Wwarn=unused-top-binds
    -Wwarn=unused-local-binds
    -Wwarn=unused-pattern-binds
    -Wwarn=type-defaults
    -fno-ignore-asserts
    -static

  build-depends:
      base >=4.7
    , containers >= 0.6.0.1
    , parsec >= 3.1.13

  exposed-modules:
    Hanoi

  other-modules:
    HOA.Format
    HOA.Parser
    HOA.Parser.Util
    HOA.Parser.Data
    HOA.Parser.Header
    HOA.Parser.Body
    HOA.Parser.LabelExpr
    HOA.Parser.AccCond
    HOA.Parser.AccName
    HOA.Parser.Properties
    HOA.Printer

  hs-source-dirs:
    src/lib

  default-language:
    Haskell2010
