name:                hanoi
version:             0.1.0.1
synopsis:            Library for automata and the HOA format
description:         A library for ω-regular automata and processing of files in HOA format
author:              Felix Klein <felix.klein@cispa.de>
                     Philippe Heim <philippe.heim@cispa.de>
                     Gideon Geier <gideon.geier@cispa.de>
                     Marvin Stenger <marvin.stenger@cispa.de>
maintainer:          Felix Klein <felix.klein@cispa.de>
                     Philippe Heim <philippe.heim@cispa.de>
                     Gideon Geier <gideon.geier@cispa.de>
                     Marvin Stenger <marvin.stenger@cispa.de>
license:             MIT
license-file:        LICENSE
category:            Automata
build-type:          Simple
cabal-version:       >=1.10

source-repository head
  type:     git
  location: https://github.com/reactive-systems/hanoi

library

  ghc-options:
    -Wall -Wno-name-shadowing -fno-ignore-asserts

  build-depends:
      base >=4.7
    , containers >= 0.6.0.1 
    , parsec


  exposed-modules:
    Hanoi

  other-modules:
    HOA.Format
    HOA.Parser
    HOA.Parser.Util
    HOA.Parser.Data
    HOA.Parser.Header
    HOA.Parser.Body
    HOA.Parser.LabelExpr
    HOA.Parser.AccCond
    HOA.Parser.AccName
    HOA.Parser.Properties
    HOA.Printer

  hs-source-dirs:
    src/lib

  default-language:
    Haskell2010
