resolver: lts-14.17
packages:
- .
extra-deps:
- git: ssh://git@git.intelligent-conception.de:4352/libraries/finite
  commit: 86a5adf9d5b56cb74780aa96ee29d3c3cc0381e3
- git: ssh://git@git.intelligent-conception.de:4352/libraries/sat
  commit: 117819b549bf5fb704ceb1268ad1db636a0d59cc
