resolver: lts-17.0
packages:
- .
extra-deps:
- git: https://github.com/kleinreact/finite.git
  commit: 8a37de506728ebbcfab05ea8ac3ff50aa34a2c9d
- git: https://github.com/reactive-systems/automata-tools-wrappers.git
  commit: fdeefb53c57600a5217a82015886f7abbf65263d
